version: '3.8'

services:
  db:
    image: mariadb
    container_name: database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: tiger
      MARIADB_USER: traefik
      MARIADB_PASSWORD: tiger
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.tcp.routers.db.rule=HostSNI(`*`)"
      - "traefik.tcp.services.db.loadbalancer.server.port=3306"
      - "traefik.tcp.routers.db.entrypoints=mysql"
    volumes:
      - './mysql/data:/var/lib/mysql'
    networks:
      - database
      - traefik
networks:
  traefik:
    external: true
  database:
    name: database