version: '3.8'

services:

  phpmyadmin:
      image: phpmyadmin
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin.entrypoints=web"
        - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.local`)"
        - "traefik.http.routers.phpmyadmin.service=phpmyadmin"
        - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik"
      networks:
        - traefik
        - database
        
networks:
  traefik:
    external: true
  database:
    external: true